- name: Converge
  hosts: all
  become: True
  roles:
    - role: role-gitlab
  vars:

    gitlab_external_url: "https://{{ ansible_hostname }}"
    gitlab_email_from: "noreply@{{ ansible_hostname }}"
    gitlab_email_display_name: "noreply@{{ ansible_hostname }}"
    gitlab_email_reply_to: "gitlab@example.com"
    gitlab_nginx_ssl_certificate: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
    gitlab_nginx_ssl_certificate_key: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
    gitlab_alertmanager_admin_email: "monitoring@example.com"

    gitlab_custom_settings:
      "nginx['ssl_verify_depth']": "1"

    gitlab_initial_root_user_password: secret_password-1234


  pre_tasks:
    # Prepare a snakeoil cert for gitlab nginx, only required for molecule
    - name: install python-openssl
      apt:
        name: python3-openssl
        state: present
    - name: create ssl cert directory
      file:
        state: directory
        path: "/etc/letsencrypt/live/{{ inventory_hostname }}/"
    - name: generate openssl private key
      openssl_privatekey:
        path: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
    - name: generate openssl certificate signing request
      openssl_csr:
        path: "/etc/letsencrypt/live/{{ inventory_hostname }}/cert.csr"
        privatekey_path: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
        common_name: "{{ inventory_hostname }}"
    - name: generate openssl self signed certificate
      openssl_certificate:
        path: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
        privatekey_path: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
        csr_path: "/etc/letsencrypt/live/{{ inventory_hostname }}/cert.csr"
        provider: selfsigned


