# - name: install python-gitlab
#   apt:
#     pkg: python-gitlab
#     state: present
#
# - name: Update the initial admin password
#   gitlab_user:
#     server_url: "{{ gitlab_external_url }}"
#     validate_certs: "{{ gitlab_api_calls_validate_certs }}"
#     login_user: root
#     login_password: "5iveL!fe"
#     name: root
#     username: root
#     password: "{{ gitlab_root_user_password }}"
#     email: "{{ gitlab_root_user_email }}"
#     state: present
#   ignore_errors: True
  # delegate_to: localhost

- name: run these commands manually now to set a new root user password
  debug:
    msg: |
      gitlab-rails console
      # wait a minute...
      user = User.where(id: 1).first
      user.password = "{{ gitlab_root_user_password }}"
      user.password_confirmation = "{{ gitlab_root_user_password }}"
      user.save!
      exit
