- name: install python-pexpect
  apt:
    name:
      - python-pexpect
      - expect
    state: present

- name: disabling gitlab signup
  become: yes
  register: gitlab_disable_signup_output
  shell: |
    expect -c 'spawn gitlab-rails console;
      expect "%s";
      send "x = ApplicationSetting.first\r";
      expect "%s";
      send "x.signup_enabled = false\r";
      expect "%s";
      send "x.save!\r";
      expect "%s";
      send "^D"'

- name: show disabling gitlab signup output
  debug:
    msg: "{{ gitlab_disable_signup_output.stdout_lines }}"


- name: set initial root password
  become: yes
  register: gitlab_set_initial_root_password_out
  shell: |
    expect -c 'spawn gitlab-rails console;
      expect "%s";
      send "user = User.where(id: 1).first\r";
      expect "%s";
      send "user.password = \"{{ gitlab_root_user_password }}\"\r";
      expect "%s";
      send "user.password_confirmation = \"{{ gitlab_root_user_password }}\"\r";
      expect "%s";
      send "user.save!\r";
      expect "%s";
      send "^D"'

- name: show set initial root password output
  debug:
    msg: "{{ gitlab_set_initial_root_password_out.stdout_lines }}"
