- name: template /etc/gitlab/gitlab.rb
  template:
    src: templates/etc/gitlab/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify:
    - gitlab-ctl reconfigure
    - gitlab-ctl restart
    - wait for workhorse

- meta: flush_handlers
